# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogwinver2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        self.textEditTitle = QtWidgets.QTextEdit(Dialog)
        self.textEditTitle.setGeometry(QtCore.QRect(15, 15, 320, 100))
        self.textEditTitle.setObjectName("textEditTitle")
        self.textEditContent = QtWidgets.QTextEdit(Dialog)
        self.textEditContent.setGeometry(QtCore.QRect(15, 125, 320, 500))
        self.textEditContent.setObjectName("textEditContent")
        self.timeEdit = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(340, 68, 125, 47))
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(340, 15, 125, 47))
        self.dateEdit.setObjectName("dateEdit")
        self.pushButtonSave = QtWidgets.QPushButton(Dialog)
        self.pushButtonSave.setGeometry(QtCore.QRect(340, 600, 125, 25))
        self.pushButtonSave.setObjectName("pushButtonSave")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Task"))
        self.pushButtonSave.setText(_translate("Dialog", "Save"))
