# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwinver3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 720)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(15, 20, 570, 660))
        self.listWidget.setObjectName("listWidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(600, 20, 345, 435))
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButtonDelete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDelete.setGeometry(QtCore.QRect(865, 655, 80, 25))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonChange = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonChange.setGeometry(QtCore.QRect(780, 655, 80, 25))
        self.pushButtonChange.setObjectName("pushButtonChange")
        self.pushButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAdd.setGeometry(QtCore.QRect(695, 655, 80, 25))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonChooseDate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonChooseDate.setGeometry(QtCore.QRect(780, 460, 80, 25))
        self.pushButtonChooseDate.setObjectName("pushButtonChooseDate")
        self.pushButtonDiscardDate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDiscardDate.setGeometry(QtCore.QRect(865, 460, 80, 25))
        self.pushButtonDiscardDate.setObjectName("pushButtonDiscardDate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diary"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete"))
        self.pushButtonChange.setText(_translate("MainWindow", "Change"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add"))
        self.pushButtonChooseDate.setText(_translate("MainWindow", "Choose Date"))
        self.pushButtonDiscardDate.setText(_translate("MainWindow", "Discard Date"))
